// const content = document.querySelector('p');

// console.log(content.classList);
// content.classList.add('error');
// content.classList.remove('error');
// content.classList.add('success');


// const paras = document.querySelectorAll('p');

// paras.forEach(p => {
//     // console.log(p.textContent);
//     if(p.textContent.includes('error')){
//         p.classList.add('error');
//     }
//     if(p.textContent.includes('success')){
//         p.classList.add('success');
//     } 
// });



//// Toggle classes: adds and removes a class with every iteration: on/off 

// const title = document.querySelector('.title');

// title.classList.toggle('test');
// title.classList.toggle('test')



//// Section 52: parents, children and siblings
/// you cannot use 'forEach on a HTML Collection, generated by the code below:

const article = document.querySelector('article');

//

// Array.from(article.children).forEach(child => {
//     child.classList.add('article-element');
// })


//// find the parent of a child element:
const title = document.querySelector('h2');

console.log(title.parentElement);
console.log(title.parentElement.parentElement);
console.log(title.nextElementSibling);



//// Find an element's sinblings
console.log(title.previousElementSibling);


////chaining
console.log(title.nextElementSibling.parentElement.children);



//// user events and event listeners. section 53
/// intersctions with the web user.



    